name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/cache@v1
      with:
        path: $HOME/.npm
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build
